Controllers/TaskDetailController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TaskHeroes.CQS.Commands;
using TaskHeroes.CQS.Queries;
using TaskHeroes.CQSInterfaces;
using TaskHeroes.Data;
using TaskHeroes.Models;

namespace TaskHeroes.Controllers
{
    public class TaskDetailController : Controller
    {
        private readonly ICommandHandler<InsertNewTaskCommand> _insertNewTaskCommandHandler;
        private readonly IQueryHandler<GetTaskByIdQuery, Task> _getTaskByIdQueryHandler;
        private readonly ICommandHandler<InsertInterestingTaskCommand> _insertInterestingTaskCommandHandler;
        public TaskDetailController(
            ICommandHandler<InsertNewTaskCommand> insertNewTaskCommandHandler,
            IQueryHandler<GetTaskByIdQuery, Task> getTaskByIdQueryHandler,
            ICommandHandler<InsertInterestingTaskCommand> insertInterestingTaskCommandHandler)
        {
            _insertNewTaskCommandHandler = insertNewTaskCommandHandler;
            _getTaskByIdQueryHandler = getTaskByIdQueryHandler;
            _insertInterestingTaskCommandHandler = insertInterestingTaskCommandHandler;
        }

        public ActionResult Index()
        {
            return View();
        }
        
        // Task Card view
        public ActionResult TaskCard(int id)
        {
            // Get task by TaskId
            var task = _getTaskByIdQueryHandler.Handle(new GetTaskByIdQuery(id));

            // Create and match the data from Task to TaskDetailModel
            var taskModel = new TaskDetailModel();
            taskModel.Id = task.Id;
            taskModel.Title = task.Title;
            taskModel.Description = task.Description;
            taskModel.JobType = task.JobType;
            taskModel.MoneyOffer = task.MoneyOffer;
            taskModel.WorkPeriod = task.WorkPeriod;
            taskModel.OffererId = task.OffererId;

            // Return TaskCard view with the corresponding model
            return View("TaskCard",taskModel);
        }
        
        // GET: TaskDetail/Details/5
        public ActionResult Details(int id)
        {
            // Get task by TaskId
            var task = _getTaskByIdQueryHandler.Handle(new GetTaskByIdQuery(id));

            // Create and match the data from Task to TaskDetailModel
            var taskModel = new TaskDetailModel();
            taskModel.Id = task.Id;
            taskModel.Title = task.Title;
            taskModel.Description = task.Description;
            taskModel.JobType = task.JobType;
            taskModel.MoneyOffer = task.MoneyOffer;
            taskModel.WorkPeriod = task.WorkPeriod;
            taskModel.OffererId = task.OffererId;

            // Return Details view with the corresponding model
            return View(taskModel);
        }

        // Task Create view
        public ActionResult TaskCreate()
        {
            return View();
        }

        // Create Task action
        [HttpPost]
        public ActionResult Create(TaskDetailModel model)
        {
            // Insert the new task into the database
            _insertNewTaskCommandHandler.Handle(new InsertNewTaskCommand(model.Title, model.Description, model.JobType, model.MoneyOffer, model.WorkPeriod, HttpContext.Session.GetInt32("userid").Value));

            // Redirect to User Profile page so user can view the new task in there list of offered postings
            return RedirectToAction("Index", "UserProfile");
        }

        // Interest Button Click action
        public ActionResult InterestButtonClick(int id)
        {
            // Get the Id of the logged in user
            var loggedInUserId = HttpContext.Session.GetInt32("userid");

            // If user is logged in, insert the new interesting task into the database so that it will show up in User Profile for review
            if (loggedInUserId != null)
                _insertInterestingTaskCommandHandler.Handle(new InsertInterestingTaskCommand(loggedInUserId.Value, id));

            // Redirect to Home page
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TaskHeroes.CQS.Commands;
using TaskHeroes.CQS.Queries;
using TaskHeroes.CQS.TransportObjects;
using TaskHeroes.CQSInterfaces;
using TaskHeroes.Models;

namespace TaskHeroes.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly IQueryHandler<GetUserDataByUserIdQuery, UserFullData> _getUserByUserIdQueryHandler;
        private readonly ICommandHandler<EditUserProfileCommand> _editUserProfileCommandHandler;

        public UserProfileController(
            IQueryHandler<GetUserDataByUserIdQuery, UserFullData> getUserByUserIdQueryHandler,
            ICommandHandler<EditUserProfileCommand> editUserProfileCommandHandler)
        {
            _getUserByUserIdQueryHandler = getUserByUserIdQueryHandler;
            _editUserProfileCommandHandler = editUserProfileCommandHandler;
        }

        // User Profile page
        public ActionResult Index()
        {
            // Display user details by the logged in user's Id
            return UserDetails(HttpContext.Session.GetInt32("userid").Value);
        }

        // User Card view
        public ActionResult UserCard(int id)
        {
            // Pull up the information of the user by Id
            var userFullData = _getUserByUserIdQueryHandler.Handle(new GetUserDataByUserIdQuery(id));

            // Create and map data from the retrieved User to the UserProfileModel
            var userModel = new UserProfileModel();
            userModel.UserId = userFullData.User.Id;
            userModel.Email = userFullData.User.Email;
            userModel.Username = userFullData.User.Username;
            userModel.Password = userFullData.User.Password;
            userModel.FirstName = userFullData.User.FirstName;
            userModel.LastName = userFullData.User.LastName;
            userModel.City = userFullData.User.City;
            userModel.Province = userFullData.User.Province;
            userModel.Description = userFullData.User.Description;
            userModel.Rating = userFullData.User.Rating;
            userModel.ListOfInterestingTasks = userFullData.ListOfInterestingTasks;
            userModel.ListOfPostingsBeingOffered = userFullData.ListOfPostingsBeingOffered;
            userModel.DateCreated = userFullData.User.DateCreated;
            userModel.Image = userFullData.User.Image;

            // Does not allow edting profile in User Card view
            userModel.AllowEditProfile = false;

            // Return the User Card view with the corresponding model
            return View(userModel);
        }

        // User Details view
        public ActionResult UserDetails(int id)
        {
            // Pull up the information of user by Id
            var userFullData = _getUserByUserIdQueryHandler.Handle(new GetUserDataByUserIdQuery(id));

            // Create and map data from the retrieved User to the UserProfileModel
            var userModel = new UserProfileModel();
            userModel.UserId = userFullData.User.Id;
            userModel.Email = userFullData.User.Email;
            userModel.Username = userFullData.User.Username;
            userModel.Password = userFullData.User.Password;
            userModel.FirstName = userFullData.User.FirstName;
            userModel.LastName = userFullData.User.LastName;
            userModel.City = userFullData.User.City;
            userModel.Province = userFullData.User.Province;
            userModel.Description = userFullData.User.Description;
            userModel.Rating = userFullData.User.Rating;
            userModel.ListOfInterestingTasks = userFullData.ListOfInterestingTasks;
            userModel.ListOfPostingsBeingOffered = userFullData.ListOfPostingsBeingOffered;
            userModel.DateCreated = userFullData.User.DateCreated;
            userModel.Image = userFullData.User.Image;

            // Allow editing profile only if the user being retrieved is also the logged in user
            userModel.AllowEditProfile = HttpContext.Session.GetInt32("userid").HasValue && id == HttpContext.Session.GetInt32("userid").Value;

            // Return User Details view with the corresponding user model
            return View(userModel);
        }

        // Edit User Profile action
        public ActionResult EditUserProfile(UserProfileModel model)
        {
            // Update the User record in the database with new data and information
            _editUserProfileCommandHandler.Handle(new EditUserProfileCommand(HttpContext.Session.GetInt32("userid").Value, model.FirstName, model.LastName, model.Email, model.City, model.Province, model.Description));

            // Redirect to the User Profile view
            return RedirectToAction("Index");
        }
    }
}

Views/UserProfile/Index.cshtml
@model UserProfileModel
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "UserProfile";

    var default_profile_picture = "~/Resources/Images/UserProfile/proflie_picture_default.png";

    var userId = Context.Session.GetString("userid");
    if (userId != null)
        Layout = "~/Views/Shared/_Layout_LogIn.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="~/css/UserProfile/UserProfile.css" />

<!-- Hidden fields for values that need to be passed into javascript -->
<input type="hidden" id="user_review" name="user_review" value=@Model.Rating />
<h1>User Profile Page</h1>
<div class="leftcolumn">
    <div class="card">
        @if (userId != null)
        {
            <img src="@Url.Content(Model.Image)" alt="User Image" style="width:100%">
        }
        else
        {
            <img src="@Url.Content(default_profile_picture)" alt="User Image" style="width:100%">
        }
        <h1>@(Model.FirstName + " " + Model.LastName)</h1>
        <form id="user_card_form">
            <div class="form-group mx-auto row margin-bottom">
                <textarea id="description" rows="4" readonly>
                        @Model.Description
                    </textarea>
            </div>
            <div class="form-group row mx-auto margin-bottom">
                <label for="user_rating" class="col-form-label">User Rating</label>
                <div class="col-sm-7">
                    <div class="stars-outer">
                        <div class="stars-inner"></div>
                    </div>
                </div>
            </div>
            <div class="form-group row mx-auto">
                <label for="member_since" class="col-form-label">Member Since</label>
                <div class="col-sm-7">
                    <input type="datetime" class="form-control-plaintext" id="member_since" value=@Model.DateCreated.Date>
                </div>
            </div>

            <p><button id="contact_btn">Contact @(Model.FirstName + " " + Model.LastName)</button></p>

            @if (Model.AllowEditProfile)
            {
                <p><button type="button" id="edit_profile_btn" data-toggle="modal" data-target="#editModal">Edit Profile</button></p>
            }
        </form>
    </div>
</div>

<div class="rightcolumn">
    <div class="user_info">
        <h1>User Info</h1>
        <form id="user_info_form">
            <div class="form-group row margin-bottom">
                <label for="username" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control-plaintext" id="username" value=@Model.Username>
                </div>
            </div>
            <div class="form-group row margin-bottom">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control-plaintext" id="email" value=@Model.Email>
                </div>
            </div>

            <div class="form-group row margin-bottom">
                <label for="fname" class="col-sm-2 col-form-label">First Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control-plaintext" id="fname" value=@Model.FirstName>
                </div>
            </div>
            <div class="form-group row margin-bottom">
                <label for="lname" class="col-sm-2 col-form-label">Last Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control-plaintext" id="lname" value=@Model.LastName>
                </div>
            </div>
            <div class="form-group row margin-bottom">
                <label for="city" class="col-sm-2 col-form-label">City</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control-plaintext" id="city" value=@Model.City>
                </div>
            </div>
            <div class="form-group row margin-bottom">
                <label for="province" class="col-sm-2 col-form-label">Province</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control-plaintext" id="province" value=@Model.Province>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="rightcolumn">
    <div class="job_history user_info">
        <h1>Interesting Tasks</h1>
        <ul class="list-group">
            @foreach (var item in Model.ListOfInterestingTasks)
            {
                <a asp-controller="TaskDetail" asp-action="Details" asp-route-id=@item.Id>
                    <li class="list-group-item">
                        <img src="~/Resources/Images/UserProfile/task_history.png" alt="task history icon" />
                        @item.Title
                    </li>
                </a>
            }

        </ul>
    </div>
</div>

<div class="rightcolumn">
    <div class="posting_history user_info">
        <h1>Posting History</h1>
        <ul class="list-group">
            @foreach (var item in Model.ListOfPostingsBeingOffered)
            {
                <a asp-controller="TaskDetail" asp-action="Details" asp-route-id=@item.Id>
                    <li class="list-group-item">
                        <img src="~/Resources/Images/UserProfile/task_history.png" alt="task history icon" />
                        @item.Title
                    </li>
                </a>
            }
        </ul>
    </div>
</div>

<!------------------------------ FORM MODAL FOR EDITING USER PROFILE ---------------------------------->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalTitle">Edit Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="UserProfile" asp-action="EditUserProfile" method="post">
                    <div class="form-group">
                        <label for="editEmail">Email address</label>
                        <input asp-for="Email" type="email" class="form-control" id="editEmail" placeholder="Enter email">
                    </div>
                    <div class="form-group">
                        <label for="editDescription">Description</label>
                        <textarea asp-for="Description" class="form-control" id="editDescription" rows="3" placeholder="Let people see how awesome you are..."></textarea>
                    </div>

                    <div class="form-group">
                        <label for="editFirstName">First Name</label>
                        <input asp-for="FirstName" type="text" class="form-control" id="editFirstName">
                    </div>

                    <div class="form-group">
                        <label for="editLastName">Last Name</label>
                        <input asp-for="LastName" type="text" class="form-control" id="editLastName">
                    </div>

                    <div class="form-group">
                        <label for="editCity">City</label>
                        <input asp-for="City" type="text" class="form-control" id="editCity">
                    </div>

                    <div class="form-group">
                        <label for="editProvince">Province</label>
                        <input asp-for="Province" type="text" class="form-control" id="editProvince">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/js/UserProfile/UserProfile.js"></script>
<script type="text/javascript" src="~/js/UserProfile/UserProfile_EventHandler.js"></script>

Views/UserProfile/UserCard.cshtml
@model UserProfileModel
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "UserCard";

    var profile_image = "~/Resources/Images/UserProfile/profile_picture_2.jpg";
    
    var userId = Context.Session.GetString("userid");
    if (userId != null)
        Layout = "~/Views/Shared/_Layout_LogIn.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="~/css/UserProfile/UserProfile.css" />

<!-- Hidden fields for values that need to be passed into javascript -->
<input type="hidden" id="user_review" name="user_review" value=@Model.Rating />
<div class="user_card mx-auto">
    <div class="card">
        <img src="@Url.Content(profile_image)" alt="John" style="width:100%">
        <h1>@(Model.FirstName + " " + Model.LastName)</h1>
        <form id="user_card_form">
            <div class="form-group mx-auto row margin-bottom">
                <textarea id="description" oninput='this.style.height = "";this.style.height = this.scrollHeight + "px"' readonly>
                        @Model.Description
                </textarea>
            </div>
            <div class="form-group row mx-auto margin-bottom">
                <label for="user_rating" class="col-form-label">User Rating</label>
                <div class="col-sm-7">
                    <div class="stars-outer">
                        <div class="stars-inner"></div>
                    </div>
                </div>
            </div>
            <div class="form-group row mx-auto">
                <label for="member_since" class="col-form-label">Member Since</label>
                <div class="col-sm-7">
                    <input type="datetime" class="form-control-plaintext" id="member_since" value=@Model.DateCreated>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript" src="~/js/UserProfile/UserProfile.js"></script>
<script type="text/javascript" src="~/js/UserProfile/UserProfile_EventHandler.js"></script>

Views/UserProfile/UserDetails.cshtml
@model UserProfileModel
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "UserDetails";
    var default_profile_picture = "~/Resources/Images/UserProfile/proflie_picture_default.png";
    var userId = Context.Session.GetString("userid");
    if (userId != null)
        Layout = "~/Views/Shared/_Layout_LogIn.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="~/css/UserProfile/UserProfile.css" />

<!-- Hidden fields for values that need to be passed into javascript -->
<input type="hidden" id="user_review" name="user_review" value=@Model.Rating />
<h1>User Profile Page</h1>
<div class="leftcolumn">
    <div class="card">
        @if (userId != null)
        {
            <img src="@Url.Content(Model.Image)" alt="User Image" style="width:100%">
        }
        else
        {
            <img src="@Url.Content(default_profile_picture)" alt="User Image" style="width:100%">
        }
        <h1>@(Model.FirstName + " " + Model.LastName)</h1>
        <form id="user_card_form">
            <div class="form-group mx-auto row margin-bottom">
                <textarea id="description" rows="4" readonly>
                        @Model.Description
                    </textarea>
            </div>
            <div class="form-group row mx-auto margin-bottom">
                <label for="user_rating" class="col-form-label">User Rating</label>
                <div class="col-sm-7">
                    <div class="stars-outer">
                        <div class="stars-inner"></div>
                    </div>
                </div>
            </div>
            <div hidden="hidden" class="form-group row margin-bottom">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control-plaintext" id="email" value=@Model.Email>
                </div>
            </div>
            <div class="form-group row mx-auto">
                <label for="member_since" class="col-form-label">Member Since</label>
                <div class="col-sm-7">
                    <input type="datetime" class="form-control-plaintext" id="member_since" value=@Model.DateCreated.Date>
                </div>
            </div>

            <p><button id="contact_btn">Contact @(Model.FirstName + " " + Model.LastName)</button></p>
        </form>
    </div>
</div>

<div class="rightcolumn">
	<div class="job_history user_info">
		<h1>Interesting Tasks</h1>
		<ul class="list-group">
			@foreach (var item in Model.ListOfInterestingTasks)
			{
				<a asp-controller="TaskDetail" asp-action="Details" asp-route-id=@item.Id>
					<li class="list-group-item">
						<img src="~/Resources/Images/UserProfile/task_history.png" alt="task history icon" />
						@item.Title
					</li>
				</a>
			}

		</ul>
	</div>
</div>

<div class="rightcolumn">
	<div class="posting_history user_info">
		<h1>Posting History</h1>
		<ul class="list-group">
			@foreach (var item in Model.ListOfPostingsBeingOffered)
			{
				<a asp-controller="TaskDetail" asp-action="Details" asp-route-id=@item.Id>
					<li class="list-group-item">
						<img src="~/Resources/Images/UserProfile/task_history.png" alt="task history icon" />
						@item.Title
					</li>
				</a>
			}
		</ul>
	</div>
</div>

<script type="text/javascript" src="~/js/UserProfile/UserProfile.js"></script>
<script type="text/javascript" src="~/js/UserProfile/UserProfile_EventHandler.js"></script>